#!/bin/sh

# Measure download with curl
# Copyright (C) 2016 Alexander Böhm <alxndr.boehm@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

export LC_ALL=C
TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S%:z)

print_help() {
	echo "Print curl logs into json"
	echo "syntax: $0 (curl arguments)"
	echo ""
	echo "$PROG, Copyright (C) 2016 Alexander Böhm <alxndr.boehm@gmail.com>"
	echo "Licensed under GPLv2. See source distribution for detailed"
	echo "copyright notices."
	echo ""
}

if [ $# -lt 1 ] ; then
	print_help
	exit 0
fi

curl -w '{
	"timestamp": "'"${TIMESTAMP}"'",
	"curl": %{json}
}\n' \
	$*
